
# پایه‌ای‌ترین سلاح‌ها

BASIC_WEAPONS = {
    'rifle': {
        'name': 'تفنگ جنگی',
        'cost': 1500,
        'power': 5,
        'range': 300,
        'speed': 0,
        'armor': 0,
        'resources': {'iron': 5, 'copper': 2},
        'category': 'basic',
        'description': 'سلاح پایه پیاده‌نظام',
        'requirements': [],
        'production_time': 1  # دقیقه
    },
    'tank': {
        'name': 'تانک جنگی',
        'cost': 850000,
        'power': 1200,
        'range': 500,
        'speed': 60,
        'armor': 800,
        'resources': {'iron': 50, 'copper': 15, 'aluminum': 10},
        'category': 'basic',
        'description': 'تانک سنگین برای نبرد زمینی',
        'requirements': ['weapon_factory'],
        'production_time': 60
    },
    'fighter_jet': {
        'name': 'جنگنده',
        'cost': 2500000,
        'power': 2000,
        'range': 1200,
        'speed': 800,
        'armor': 300,
        'resources': {'aluminum': 30, 'titanium': 15, 'copper': 20},
        'category': 'basic',
        'description': 'جنگنده چندمنظوره',
        'requirements': ['weapon_factory', 'power_plant'],
        'production_time': 120
    },
    'helicopter': {
        'name': 'هلیکوپتر جنگی',
        'cost': 2800000,
        'power': 2400,
        'range': 1500,
        'resources': {'aluminum': 30, 'iron': 20, 'copper': 10},
        'category': 'basic',
        'description': 'هلیکوپتر نظامی',
        'requirements': ['weapon_factory'],
        'production_time': 90
    },
    'jet': {
        'name': 'جت جنگی',
        'cost': 4500000,
        'power': 3200,
        'range': 2000,
        'speed': 1200,
        'armor': 400,
        'resources': {'aluminum': 40, 'iron': 25, 'copper': 15, 'titanium': 5},
        'category': 'basic',
        'description': 'جت پیشرفته',
        'requirements': ['weapon_factory', 'power_plant'],
        'production_time': 150
    },
    'drone': {
        'name': 'پهپاد نظامی',
        'cost': 180000,
        'power': 800,
        'range': 1000,
        'speed': 200,
        'armor': 50,
        'resources': {'aluminum': 10, 'copper': 8, 'lithium': 5},
        'category': 'basic',
        'description': 'پهپاد مسلح با قابلیت نظارت',
        'requirements': ['weapon_factory'],
        'production_time': 30
    },
    'warship': {
        'name': 'ناو جنگی',
        'cost': 2500000,
        'power': 3500,
        'range': 1500,
        'speed': 45,
        'armor': 1500,
        'resources': {'iron': 100, 'aluminum': 50, 'copper': 30},
        'category': 'basic',
        'description': 'کشتی جنگی سنگین',
        'requirements': ['weapon_factory', 'refinery'],
        'production_time': 180
    },
    'submarine': {
        'name': 'زیردریایی',
        'cost': 4200000,
        'power': 4800,
        'range': 2000,
        'speed': 35,
        'armor': 2000,
        'resources': {'iron': 80, 'aluminum': 40, 'uranium': 5},
        'category': 'basic',
        'description': 'زیردریایی نظامی',
        'requirements': ['weapon_factory', 'refinery'],
        'production_time': 240
    },
    'destroyer': {
        'name': 'ناوشکن',
        'cost': 3800000,
        'power': 5200,
        'range': 1800,
        'speed': 50,
        'armor': 1800,
        'resources': {'iron': 90, 'aluminum': 45, 'copper': 25, 'titanium': 3},
        'category': 'basic',
        'description': 'ناوشکن پیشرفته',
        'requirements': ['weapon_factory', 'refinery'],
        'production_time': 200
    },
    'aircraft_carrier': {
        'name': 'ناو هواپیمابر',
        'cost': 12500000,
        'power': 15000,
        'range': 2500,
        'speed': 30,
        'armor': 5000,
        'resources': {'iron': 200, 'aluminum': 100, 'titanium': 20, 'uranium': 10},
        'category': 'basic',
        'description': 'ناو هواپیمابر غول‌پیکر',
        'requirements': ['weapon_factory', 'refinery', 'power_plant'],
        'production_time': 480
    },
    'strategic_bomber': {
        'name': 'بمب‌افکن استراتژیک',
        'cost': 8500000,
        'power': 4500,
        'range': 4500,
        'speed': 400,
        'armor': 800,
        'resources': {'aluminum': 60, 'titanium': 25, 'fuel': 50},
        'category': 'basic',
        'description': 'بمب‌افکن سنگین',
        'requirements': ['weapon_factory', 'refinery'],
        'production_time': 300
    }
}
