
# موشک‌های مخصوص و پیشرفته

SPECIAL_MISSILES = {
    'trident2_conventional': {
        'name': 'Trident 2 غیر هسته‌ای',
        'cost': 0,
        'power': 1000,
        'range': 5000,
        'speed': 4000,
        'armor': 150,
        'resources': {'simple_bomb': 13, 'ballistic_missile': 1, 'coal': 140},
        'category': 'special_missiles',
        'description': 'موشک Trident 2 با کلاهک معمولی',
        'requirements': ['weapon_factory', 'refinery'],
        'production_time': 300,
        'submarine_launch': True
    },
    'trident2_nuclear': {
        'name': 'Trident 2 هسته‌ای',
        'cost': 190000,
        'power': 30000,
        'range': 5000,
        'speed': 4000,
        'armor': 150,
        'resources': {'nuclear_bomb': 13, 'ballistic_missile': 1, 'coal': 140},
        'category': 'special_missiles',
        'description': 'موشک Trident 2 با کلاهک هسته‌ای',
        'requirements': ['weapon_factory', 'refinery', 'power_plant'],
        'production_time': 360,
        'submarine_launch': True,
        'radioactive': True
    },
    'satan2_conventional': {
        'name': 'Satan2 غیر هسته‌ای',
        'cost': 0,
        'power': 940,
        'range': 4500,
        'speed': 5000,
        'armor': 200,
        'resources': {'simple_bomb': 10, 'ballistic_missile': 1, 'coal': 140},
        'category': 'special_missiles',
        'description': 'موشک Satan2 با کلاهک معمولی',
        'requirements': ['weapon_factory', 'refinery'],
        'production_time': 280,
        'multiple_warheads': True
    },
    'satan2_nuclear': {
        'name': 'Satan2 هسته‌ای',
        'cost': 160000,
        'power': 21000,
        'range': 4500,
        'speed': 5000,
        'armor': 200,
        'resources': {'nuclear_bomb': 10, 'ballistic_missile': 1, 'coal': 140},
        'category': 'special_missiles',
        'description': 'موشک Satan2 با کلاهک هسته‌ای',
        'requirements': ['weapon_factory', 'refinery', 'power_plant'],
        'production_time': 340,
        'multiple_warheads': True,
        'radioactive': True
    },
    'df41_nuclear': {
        'name': 'DF-41 هسته‌ای',
        'cost': 130000,
        'power': 18000,
        'range': 4000,
        'speed': 4500,
        'armor': 180,
        'resources': {'nuclear_bomb': 8, 'ballistic_missile': 1, 'coal': 140},
        'category': 'special_missiles',
        'description': 'موشک چینی DF-41',
        'requirements': ['weapon_factory', 'refinery', 'power_plant'],
        'production_time': 320,
        'radioactive': True
    },
    'tomahawk_conventional': {
        'name': 'Tomahawk غیر هسته‌ای',
        'cost': 12000,
        'power': 700,
        'range': 1500,
        'speed': 1200,
        'armor': 50,
        'resources': {'ballistic_missile': 1, 'simple_bomb': 1, 'iron': 10, 'sulfur': 120},
        'category': 'special_missiles',
        'description': 'موشک کروز آمریکایی',
        'requirements': ['weapon_factory'],
        'production_time': 120,
        'cruise_missile': True
    },
    'tomahawk_nuclear': {
        'name': 'Tomahawk هسته‌ای',
        'cost': 18000,
        'power': 3000,
        'range': 1500,
        'speed': 1200,
        'armor': 50,
        'resources': {'nuclear_bomb': 1, 'ballistic_missile': 1, 'iron': 30, 'coal': 20},
        'category': 'special_missiles',
        'description': 'موشک کروز با کلاهک هسته‌ای',
        'requirements': ['weapon_factory', 'power_plant'],
        'production_time': 150,
        'cruise_missile': True,
        'radioactive': True
    },
    'kalibr_conventional': {
        'name': 'Kalibr غیر هسته‌ای',
        'cost': 12000,
        'power': 650,
        'range': 1500,
        'speed': 1100,
        'armor': 45,
        'resources': {'ballistic_missile': 1, 'simple_bomb': 1, 'iron': 10, 'sulfur': 30},
        'category': 'special_missiles',
        'description': 'موشک کروز روسی',
        'requirements': ['weapon_factory'],
        'production_time': 110,
        'cruise_missile': True
    }
}
