
# تجهیزات حمل و نقل و لجستیک

TRANSPORT_EQUIPMENT = {
    'armored_truck': {
        'name': 'کامیون زرهی',
        'cost': 450000,
        'power': 200,
        'range': 400,
        'speed': 80,
        'armor': 400,
        'resources': {'iron': 30, 'aluminum': 15},
        'category': 'transport',
        'description': 'کامیون زرهی برای حمل منابع',
        'requirements': ['weapon_factory'],
        'production_time': 45,
        'cargo_capacity': 1000,
        'convoy_security': 25
    },
    'cargo_helicopter': {
        'name': 'هلیکوپتر باری',
        'cost': 2200000,
        'power': 800,
        'range': 600,
        'speed': 250,
        'armor': 150,
        'resources': {'aluminum': 25, 'iron': 20, 'copper': 10},
        'category': 'transport',
        'description': 'هلیکوپتر برای حمل سریع',
        'requirements': ['weapon_factory'],
        'production_time': 90,
        'cargo_capacity': 2000,
        'convoy_security': 40,
        'speed_bonus': 50
    },
    'cargo_plane': {
        'name': 'هواپیمای باری',
        'cost': 6500000,
        'power': 1500,
        'range': 2000,
        'speed': 600,
        'armor': 200,
        'resources': {'aluminum': 40, 'iron': 30, 'titanium': 8},
        'category': 'transport',
        'description': 'هواپیمای باری برای انتقال بین‌المللی',
        'requirements': ['weapon_factory', 'power_plant'],
        'production_time': 180,
        'cargo_capacity': 5000,
        'convoy_security': 60,
        'speed_bonus': 75
    },
    'escort_frigate': {
        'name': 'ناوچه اسکورت',
        'cost': 3800000,
        'power': 2800,
        'range': 1200,
        'speed': 45,
        'armor': 1200,
        'resources': {'iron': 60, 'aluminum': 30, 'copper': 20},
        'category': 'transport',
        'description': 'ناوچه محافظت از کاروان‌های دریایی',
        'requirements': ['weapon_factory', 'refinery'],
        'production_time': 150,
        'convoy_security': 80,
        'naval_escort': True
    },
    'logistics_drone': {
        'name': 'پهپاد لجستیک',
        'cost': 850000,
        'power': 400,
        'range': 800,
        'speed': 200,
        'armor': 100,
        'resources': {'aluminum': 15, 'lithium': 8, 'copper': 12},
        'category': 'transport',
        'description': 'پهپاد برای حمل کوچک و سریع',
        'requirements': ['weapon_factory'],
        'production_time': 60,
        'convoy_security': 30,
        'stealth': True,
        'speed_bonus': 40
    },
    'heavy_transport': {
        'name': 'ترابری سنگین',
        'cost': 1200000,
        'power': 600,
        'range': 500,
        'speed': 60,
        'armor': 800,
        'resources': {'iron': 45, 'aluminum': 20, 'copper': 15},
        'category': 'transport',
        'description': 'خودروی حمل سنگین',
        'requirements': ['weapon_factory'],
        'production_time': 75,
        'cargo_capacity': 3000,
        'convoy_security': 45
    },
    'supply_ship': {
        'name': 'کشتی تدارکات',
        'cost': 4500000,
        'power': 1200,
        'range': 3000,
        'speed': 35,
        'armor': 1500,
        'resources': {'iron': 80, 'aluminum': 40, 'copper': 25},
        'category': 'transport',
        'description': 'کشتی بزرگ حمل منابع',
        'requirements': ['weapon_factory', 'refinery'],
        'production_time': 200,
        'cargo_capacity': 8000,
        'convoy_security': 70,
        'naval': True
    },
    'stealth_transport': {
        'name': 'ترابری پنهان‌کار',
        'cost': 8200000,
        'power': 2000,
        'range': 1500,
        'speed': 120,
        'armor': 600,
        'resources': {'titanium': 15, 'aluminum': 50, 'uranium': 5},
        'category': 'transport',
        'description': 'وسیله نقلیه پنهان‌کار پیشرفته',
        'requirements': ['weapon_factory', 'power_plant', 'refinery'],
        'production_time': 300,
        'cargo_capacity': 1500,
        'convoy_security': 90,
        'speed_bonus': 60,
        'stealth': True
    },
    'tanker_aircraft': {
        'name': 'هواپیمای سوخت‌رسان',
        'cost': 5800000,
        'power': 1000,
        'range': 4000,
        'speed': 450,
        'armor': 300,
        'resources': {'aluminum': 60, 'iron': 40, 'copper': 20, 'titanium': 8},
        'category': 'transport',
        'description': 'هواپیمای سوخت‌رسان که برد جت‌ها را افزایش می‌دهد',
        'requirements': ['weapon_factory', 'power_plant', 'refinery'],
        'production_time': 250,
        'convoy_security': 50,
        'range_extender': True,
        'jet_range_bonus': 2000  # افزایش 2000 کیلومتر برد برای جت‌ها
    },
    'aircraft_carrier_transport': {
        'name': 'ناو هواپیمابر (حمل‌ونقل)',
        'cost': 12500000,
        'power': 8000,
        'range': 5000,
        'speed': 30,
        'armor': 6000,
        'resources': {'iron': 200, 'aluminum': 100, 'titanium': 25, 'uranium': 15, 'copper': 80},
        'category': 'transport',
        'description': 'ناو هواپیمابر که جت‌ها را به مناطق دوردست می‌برد',
        'requirements': ['weapon_factory', 'power_plant', 'refinery'],
        'production_time': 400,
        'convoy_security': 95,
        'range_extender': True,
        'jet_range_bonus': 3000,  # افزایش 3000 کیلومتر برد برای جت‌ها
        'naval': True,
        'mobile_airbase': True
    }
}
